# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "boxcutter/ubuntu1504"
  config.vm.network :private_network, ip: "192.168.56.4"
  config.ssh.forward_agent = true
  config.vm.synced_folder "../", "/php-project"
  config.vm.provision "shell", path: "script.sh"
end
